{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "valse.serviceAccountName" . }}
  namespace: {{.Values.namespace}}
  labels:
    {{- include "valse.labels" . | nindent 4 }}
{{- end }}
